name: win_spark_spacy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipywidgets
  - notebook
  - jupyterlab
  - pandas
  - scikit-learn
  - imbalanced-learn
  - pyarrow
  - anaconda::pyrush
  - conda-forge::jupytext
  - pip:
    - medspacy
    - loguru
    - pyrush
    - py4jrush
    - findspark
    - pyspark==3.4.2
    - spark-nlp==5.3.3
    - py7zr
prefix: D:\conda_env_jianlin\win_spark_spacy
