name: win_dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - conda-forge::faiss-cpu
  - menuinst
  - pytorch::torchtext
  - pip
  - ipywidgets
  - ipympl
  - cython
  - notebook
  - jupyterlab
  - unqlite
  - conda-forge::torchinfo
  - conda-forge::imbalanced-learn
  - conda-forge::scikit-learn
  - conda-forge::jupytext
  - pip:
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - beautifulsoup4
    - bioc
    - simpletransformers
    - nltk
    - numba
    - numpy
    - sqlalchemy
    - ipympl
    - numexpr
    - statsmodels
    - bioc==2.0
    - tqdm
    - spacy
    - tensorboard
    - pytest
    - setuptools
    - wheel
    - scipy
    - joblib
    - qdrant-client
    - jupyterlab-widgets
    - matplotlib
    - itsdangerous
    - accelerate
    - lightning
    - loguru
    - findspark
    - install-jdk
    - tensorflow
    - tensorflow-text
    - pyspark==3.4.2
    - spark-nlp==5.3.3
    - gensim
    - python-dateutil
    - pyodbc
    - xgboost
    - xlrd
    - spark-nlp-display
    - openpyxl
    - findspark
    - flask
    - flask-restful
    - keras
    - loguru
    - lxml    
    - markdown
    - mlflow
    - multiprocess
    - murmurhash      
    - oauthlib
    - openpyxl    
    - optimum
    - pandas
    - preshed
    - protobuf
    - py4j
    - py7zr
    - pyarrow
    - pydantic
    - sqlalchemy
    - sqlparse
    - statsmodels
    - tensorflow
    - tokenizers
    - torchmetrics
    - unidecode
    - wandb
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - ninja
    - pyyaml
    - requests
    - dspy-ai
    - langchain
    - langchain-core
    - langchain-community
    - langchain-experimental
    - langgraph
    - langchain-cli
    - langsmith
    - langchain-openai
    - langchain-huggingface
    - langchain-anthropic
 
prefix: D:\annaconda_env_jianlin\win_dev
