name: base
channels:
  - anaconda
  - nvidia
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  # - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - nvidia/label/cuda-12.4.0::cuda-nvcc
  - faiss-gpu
  - conda-forge:cudnn
  - pytorch::torchtext
  # github runner doesn't have a gpu, it seems not working , disable for now. 
  # might work using https://github.com/gpgpu-sim/gpgpu-sim_distribution, check it later
  # - nvidia/label/cuda-11.8.0::cutatoolkit
  - pandas
  - pip
  - numpy
  - openpyxl=3.0.10
  - sqlalchemy
  - ipympl
  - cython=0.29
  - loguru
  - jupyterlab
  - xlrd=2.0.1
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - conda-forge::pyarrow=14.0.1
  - anaconda::pyrush
  - pip:
    # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/layers
    # may consider torchdynamo in later versions
    # https://pytorch.org/docs/stable/dynamo/installation.html
    - setuptools==65
    # tmp solution to fix the pip install medspacy     
    # - git+https://github.com/jianlins/medspacy.git
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - transformers>=4.31.0
    # dependency version conflict, fix it later
    # - medpspacy-io
    - simpletransformers
    - nltk
    - bioc==2.0
    - tqdm==4.65
    - tensorboard
    - pytest
    - wheel
    - joblib
    - itsdangerous<2.1.0
    - accelerate
    - lightning==2.1.2
    - pyspark==3.4.2
    - spark-nlp==5.3.3
    - gensim
    - git+https://github.com/HarryCaveMan/sklearn-crfsuite.git
    - pyodbc
    # torchserve
    - torchserve
    - torch-model-archiver
    - torch-workflow-archiver
    # additional dependencies required by torchserve
    # https://github.dev/pytorch/serve/blob/master/requirements/common_gpu.txt
    # https://github.dev/pytorch/serve/blob/master/requirements/common.txt
    # https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/requirements.txt
    - nvgpu
    - optimum
    - psutil==5.9.5
    - requests
    - captum==0.6.0
    - packaging
    - nvidia-ml-py
    - pyyaml
    - ninja
    # torchserve's client
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - flask
    - flask-restful
    - ninja
    - torch-ort
    - onnxruntime-gpu
    - jupyterlab-freeze
    - scipy
    - optuna
    - sympy
    - statsmodels
    - pickleshare
    - langchain
    - langchain-core
    - langchain-community
    - langchain-experimental
    - langgraph
    - langchain-cli
    - langserve[all]    
    - langsmith
    - langchain-openai
    - langchain-huggingface
    - langchain-anthropic    